apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: argocd-resources-policy
  namespace: argocd
spec:
  resourceSelectors:
    # Namespace
    - apiVersion: v1
      kind: Namespace
      name: argocd
    # Core Resources
    - apiVersion: v1
      kind: ServiceAccount
      namespace: argocd
    - apiVersion: v1
      kind: Secret
      namespace: argocd
    - apiVersion: v1
      kind: ConfigMap
      namespace: argocd
    - apiVersion: v1
      kind: Service
      namespace: argocd
    # RBAC Resources
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      namespace: argocd
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      namespace: argocd
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
    # Deployments
    - apiVersion: apps/v1
      kind: Deployment
      namespace: argocd
    - apiVersion: apps/v1
      kind: StatefulSet
      namespace: argocd
    # Networking
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      namespace: argocd
    # Custom Resources
    - apiVersion: argoproj.io/v1alpha1
      kind: Application
      namespace: argocd
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      namespace: argocd
    - apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      namespace: argocd
  placement:
    clusterAffinity:
      clusterNames:
        - member1
