apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
 name: argoevents-crds-policy
spec:
 resourceSelectors:
   - apiVersion: apiextensions.k8s.io/v1
     kind: CustomResourceDefinition  
     name: eventbus.argoproj.io
   - apiVersion: apiextensions.k8s.io/v1
     kind: CustomResourceDefinition
     name: eventsources.argoproj.io 
   - apiVersion: apiextensions.k8s.io/v1
     kind: CustomResourceDefinition
     name: sensors.argoproj.io
 placement:
   clusterAffinity:
     clusterNames:
       - member1
   spreadConstraints:
     - maxGroups: 1
       minGroups: 1
       spreadByField: cluster
 propagationMode: BidirectionalSync
